version: '3.7'

services:
  zabbix-server:
    image: zabbix/zabbix-server-mysql:latest
    container_name: zabbix-server
    environment:
      - DB_SERVER_HOST=zabbix-db
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix_password
      - MYSQL_DATABASE=zabbix
    depends_on:
      - zabbix-db
    ports:
      - "10051:10051"
    networks:
      - zabbix-net
    restart: always

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:latest
    container_name: zabbix-web
    environment:
      - DB_SERVER_HOST=zabbix-db
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix_password
      - MYSQL_DATABASE=zabbix
      - ZBX_SERVER_HOST=zabbix-server
      - PHP_TZ=Europe/Kiev
    ports:
      - "8080:8080"
    depends_on:
      - zabbix-server
    networks:
      - zabbix-net
    restart: always

  zabbix-db:
    image: mysql:5.7
    container_name: zabbix-db
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix_password
      - MYSQL_DATABASE=zabbix
    volumes:
      - zabbix-db-data:/var/lib/mysql
    networks:
      - zabbix-net
    restart: always

networks:
  zabbix-net:
    driver: bridge

volumes:
  zabbix-db-data:
